// astramem export-md — render a repo-visible MEMORY.md digest (issue #34).
//
// Recalls the top-K hits per requested type for the resolved project and
// writes a committed markdown snapshot. This is deliberately narrower than
// the SessionStart recall hook (issues #31/#32):
//   - SessionStart recall injects LIVE, machine-local session context on every
//     session start, unfiltered by type, and is never written to disk.
//   - export-md produces a COMMITTED, human/CI-readable snapshot restricted to
//     deliberate memory types (decision/lesson by default) — free-form or
//     auto-distilled atoms are excluded by default since a git sink is a much
//     higher-stakes destination than a transient session prompt.
//
// The wire RecallRequest has no per-type filter (see src/contracts/wire.ts),
// so this command over-fetches with a single semantic query and buckets the
// results by `hit.type` client-side, keeping the top --k per bucket.
//
// Re-scrub at export time (architect finding): ingest-time scrubbing runs
// once, when the atom was first captured. Scrub patterns evolve, and a git
// sink is forever (history, forks, CI logs) in a way a local daemon's store
// is not — so every export re-runs scrubWithLabels() over each atom's text
// immediately before it's written to the committed file.
//
// write-if-different: if the rendered content is byte-identical to what's
// already on disk, the file is left untouched — this command is expected to
// run on every SessionEnd (via the opt-in hook) and must not manufacture a
// git diff when nothing actually changed.
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { RecallRequestSchema } from '../contracts/wire.ts';
import type { RecallHit } from '../contracts/wire.ts';
import type { Provider } from '../contracts/selector.ts';
import type { MemoryProvider } from '../contracts/provider.ts';
import { resolveProvider } from '../lib/selector.ts';
import { resolveProject } from '../lib/project.ts';
import { scrubWithLabels } from '../lib/scrub.ts';

/** Injected opts for tests. */
export interface ExportMdOpts {
  provider?: Provider;
  _provider?: MemoryProvider;
}

export const DEFAULT_OUT = '.claude/astramem/MEMORY.md';
export const DEFAULT_TYPES = ['decision', 'lesson'] as const;
export const DEFAULT_K = 10;

function csvTypes(raw: string | undefined): string[] {
  if (raw === undefined) return [...DEFAULT_TYPES];
  const parts = raw.split(',').map(s => s.trim()).filter(Boolean);
  return parts.length === 0 ? [...DEFAULT_TYPES] : parts;
}

/**
 * Bucket hits by type (case-insensitive), keep only requested types, sort
 * each bucket by score descending, and truncate to k per bucket.
 */
function bucketByType(hits: RecallHit[], types: string[], k: number): Map<string, RecallHit[]> {
  const wanted = new Map(types.map(t => [t.toLowerCase(), t]));
  const buckets = new Map<string, RecallHit[]>();
  for (const t of types) buckets.set(t, []);

  for (const hit of hits) {
    const canonical = wanted.get(hit.type.toLowerCase());
    if (canonical === undefined) continue;
    buckets.get(canonical)!.push(hit);
  }

  for (const [t, list] of buckets) {
    list.sort((a, b) => b.score - a.score);
    buckets.set(t, list.slice(0, k));
  }

  return buckets;
}

/**
 * Render the markdown digest. Re-scrubs each atom's text as it's rendered
 * (see module comment). No wall-clock timestamp — that would churn the file
 * on every run regardless of content, defeating write-if-different.
 *
 * RecallHit carries no created-at/age field on the wire (see
 * src/contracts/wire.ts RecallHitSchema) — relevance `score` is the only
 * ranking signal available, so it stands in for the "age" column called out
 * in the issue.
 */
export function renderMarkdown(opts: {
  project: string;
  types: string[];
  buckets: Map<string, RecallHit[]>;
}): string {
  const { project, types, buckets } = opts;
  const lines: string[] = [];

  lines.push('# MEMORY.md');
  lines.push('');
  lines.push('> Auto-generated by `astramem export-md` — do not hand-edit; this file is');
  lines.push('> overwritten on every export. To add memories, use `/remember` (or');
  lines.push('> `astramem remember`).');
  lines.push('>');
  lines.push('> Text below is re-scrubbed for secrets at export time — ingest-time');
  lines.push('> scrubbing alone is not sufficient for a file committed to git.');
  lines.push('>');
  lines.push(`> Project: \`${project}\` · Types: ${types.map(t => `\`${t}\``).join(', ')}`);

  for (const type of types) {
    lines.push('');
    lines.push(`## ${type}`);
    lines.push('');
    const hits = buckets.get(type) ?? [];
    if (hits.length === 0) {
      lines.push('_(no memories recalled)_');
      continue;
    }
    for (const hit of hits) {
      const { output } = scrubWithLabels(hit.text);
      const clean = output.replace(/\s+/g, ' ').trim();
      lines.push(`- \`${hit.id}\` [${hit.type}, score ${hit.score.toFixed(2)}] — ${clean}`);
    }
  }

  lines.push('');
  return lines.join('\n');
}

function buildQuery(types: string[]): string {
  return `${types.join(' ')} — key decisions and lessons for this project`;
}

/**
 * Run the `astramem export-md` subcommand.
 *
 * Flags:
 *   --project <name>  default via resolveProject({ cwd })
 *   --out <path>      default .claude/astramem/MEMORY.md (resolved against cwd)
 *   --k <N>           per-type cap, default 10
 *   --types <csv>     default "decision,lesson" — deliberate types only
 *   --cwd <path>      base for --out resolution + resolveProject() fallback
 *
 * Returns 0 on success (written or unchanged), 3 on backend error.
 */
export async function runExportMd(args: string[], opts: ExportMdOpts = {}): Promise<number> {
  let projectFlag: string | undefined;
  let outFlag: string | undefined;
  let k = DEFAULT_K;
  let typesFlag: string | undefined;
  let cwd: string | undefined;

  for (let i = 0; i < args.length; i++) {
    switch (args[i]) {
      case '--project':
        projectFlag = args[i + 1];
        i++;
        break;
      case '--out':
        outFlag = args[i + 1];
        i++;
        break;
      case '--k':
        k = parseInt(args[i + 1] ?? String(DEFAULT_K), 10);
        i++;
        break;
      case '--types':
        typesFlag = args[i + 1];
        i++;
        break;
      case '--cwd':
        cwd = args[i + 1];
        i++;
        break;
      default:
        break;
    }
  }

  const baseCwd = cwd ?? process.cwd();
  const project = resolveProject({ flag: projectFlag, cwd: baseCwd });
  const types = csvTypes(typesFlag);
  const outPath = resolve(baseCwd, outFlag ?? DEFAULT_OUT);

  // Over-fetch enough hits to plausibly fill k per type bucket, capped at the
  // wire schema's max (100) since there's no per-type filter on the request.
  const fetchK = Math.min(100, Math.max(k * types.length * 3, 30));

  const reqParsed = RecallRequestSchema.safeParse({
    query: buildQuery(types),
    k: fetchK,
    project,
  });
  if (!reqParsed.success) {
    process.stderr.write(`astramem export-md: invalid arguments — ${reqParsed.error.message}\n`);
    return 3;
  }
  const req = reqParsed.data;

  let provider: MemoryProvider;
  try {
    if (opts._provider) {
      provider = opts._provider;
    } else {
      const sel = await resolveProvider({ flag: opts.provider });
      provider = sel.provider;
    }
  } catch (e) {
    process.stderr.write(`astramem export-md: selector error — ${(e as Error).message}\n`);
    return 3;
  }

  try {
    let timedOut = false;
    const timeoutHandle = setTimeout(() => { timedOut = true; }, 5000);
    const response = await Promise.race([
      provider.recall(req),
      new Promise<never>((_, reject) => setTimeout(() => reject(new Error('recall timed out after 5s')), 5000)),
    ]);
    clearTimeout(timeoutHandle);
    if (timedOut) {
      process.stderr.write('astramem export-md: timed out\n');
      return 3;
    }

    const buckets = bucketByType(response.hits, types, k);
    const content = renderMarkdown({ project, types, buckets });

    let changed = true;
    if (existsSync(outPath)) {
      const existing = readFileSync(outPath, 'utf-8');
      if (existing === content) changed = false;
    }

    const total = [...buckets.values()].reduce((sum, list) => sum + list.length, 0);
    if (changed) {
      mkdirSync(dirname(outPath), { recursive: true });
      writeFileSync(outPath, content, 'utf-8');
      process.stdout.write(`astramem export-md: wrote ${outPath} (${total} atoms)\n`);
    } else {
      process.stdout.write(`astramem export-md: ${outPath} unchanged (${total} atoms)\n`);
    }
    return 0;
  } catch (e) {
    process.stderr.write(`astramem export-md: backend error — ${(e as Error).message}\n`);
    return 3;
  }
}
